version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
